### ISSUE TITLE
op3 simulation not responding

### ISSUE THREAD

**Issue by hayday100** [ROBOTIS-GIT/ROBOTIS-OP3#43] opened 2018-06-21 11:12 UTC
I am trying the op3 Gazebo simulation.  I started roscore in one terminal.  
In the rest three terminals, I need to use Python2.7 virtualenv and run the roslaunch commands and attached the output.  Other than some warnings (... for same type) and serial port error (which should not affect a simulation), I don't see anything seriously wrong.  They all talk to the same master node on local port 11311.  But the issue is the simulation is not responding to any demo buttons.  I had the simulation worked once but now it no longer works and I don't know how to get it to work again.  Please help!  Thanks! 

#in second terminal
roslaunch op3_gazebo robotis_world.launch

```


xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
xacro.py is deprecated; please use xacro instead
started roslaunch server http://home-desktop:46235/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /robotis_op3/head_pan_position/joint: head_pan
 * /robotis_op3/head_pan_position/pid/d: 0.0
 * /robotis_op3/head_pan_position/pid/i: 0.0
 * /robotis_op3/head_pan_position/pid/p: 5.0
 * /robotis_op3/head_pan_position/type: effort_controller...
 * /robotis_op3/head_tilt_position/joint: head_tilt
 * /robotis_op3/head_tilt_position/pid/d: 0.0
 * /robotis_op3/head_tilt_position/pid/i: 0.0
 * /robotis_op3/head_tilt_position/pid/p: 5.0
 * /robotis_op3/head_tilt_position/type: effort_controller...
 * /robotis_op3/joint_state_controller/publish_rate: 50
 * /robotis_op3/joint_state_controller/type: joint_state_contr...
 * /robotis_op3/l_ank_pitch_position/joint: l_ank_pitch
 * /robotis_op3/l_ank_pitch_position/pid/d: 0.0
 * /robotis_op3/l_ank_pitch_position/pid/i: 0.0
 * /robotis_op3/l_ank_pitch_position/pid/p: 50.0
 * /robotis_op3/l_ank_pitch_position/type: effort_controller...
 * /robotis_op3/l_ank_roll_position/joint: l_ank_roll
 * /robotis_op3/l_ank_roll_position/pid/d: 0.0
 * /robotis_op3/l_ank_roll_position/pid/i: 0.0
 * /robotis_op3/l_ank_roll_position/pid/p: 50.0
 * /robotis_op3/l_ank_roll_position/type: effort_controller...
 * /robotis_op3/l_el_position/joint: l_el
 * /robotis_op3/l_el_position/pid/d: 0.0
 * /robotis_op3/l_el_position/pid/i: 0.0
 * /robotis_op3/l_el_position/pid/p: 10.0
 * /robotis_op3/l_el_position/type: effort_controller...
 * /robotis_op3/l_hip_pitch_position/joint: l_hip_pitch
 * /robotis_op3/l_hip_pitch_position/pid/d: 0.0
 * /robotis_op3/l_hip_pitch_position/pid/i: 0.0
 * /robotis_op3/l_hip_pitch_position/pid/p: 50.0
 * /robotis_op3/l_hip_pitch_position/type: effort_controller...
 * /robotis_op3/l_hip_roll_position/joint: l_hip_roll
 * /robotis_op3/l_hip_roll_position/pid/d: 0.0
 * /robotis_op3/l_hip_roll_position/pid/i: 0.0
 * /robotis_op3/l_hip_roll_position/pid/p: 50.0
 * /robotis_op3/l_hip_roll_position/type: effort_controller...
 * /robotis_op3/l_hip_yaw_position/joint: l_hip_yaw
 * /robotis_op3/l_hip_yaw_position/pid/d: 0.0
 * /robotis_op3/l_hip_yaw_position/pid/i: 0.0
 * /robotis_op3/l_hip_yaw_position/pid/p: 50.0
 * /robotis_op3/l_hip_yaw_position/type: effort_controller...
 * /robotis_op3/l_knee_position/joint: l_knee
 * /robotis_op3/l_knee_position/pid/d: 0.0
 * /robotis_op3/l_knee_position/pid/i: 0.0
 * /robotis_op3/l_knee_position/pid/p: 50.0
 * /robotis_op3/l_knee_position/type: effort_controller...
 * /robotis_op3/l_sho_pitch_position/joint: l_sho_pitch
 * /robotis_op3/l_sho_pitch_position/pid/d: 0.0
 * /robotis_op3/l_sho_pitch_position/pid/i: 0.0
 * /robotis_op3/l_sho_pitch_position/pid/p: 10.0
 * /robotis_op3/l_sho_pitch_position/type: effort_controller...
 * /robotis_op3/l_sho_roll_position/joint: l_sho_roll
 * /robotis_op3/l_sho_roll_position/pid/d: 0.0
 * /robotis_op3/l_sho_roll_position/pid/i: 0.0
 * /robotis_op3/l_sho_roll_position/pid/p: 10.0
 * /robotis_op3/l_sho_roll_position/type: effort_controller...
 * /robotis_op3/r_ank_pitch_position/joint: r_ank_pitch
 * /robotis_op3/r_ank_pitch_position/pid/d: 0.0
 * /robotis_op3/r_ank_pitch_position/pid/i: 0.0
 * /robotis_op3/r_ank_pitch_position/pid/p: 50.0
 * /robotis_op3/r_ank_pitch_position/type: effort_controller...
 * /robotis_op3/r_ank_roll_position/joint: r_ank_roll
 * /robotis_op3/r_ank_roll_position/pid/d: 0.0
 * /robotis_op3/r_ank_roll_position/pid/i: 0.0
 * /robotis_op3/r_ank_roll_position/pid/p: 50.0
 * /robotis_op3/r_ank_roll_position/type: effort_controller...
 * /robotis_op3/r_el_position/joint: r_el
 * /robotis_op3/r_el_position/pid/d: 0.0
 * /robotis_op3/r_el_position/pid/i: 0.0
 * /robotis_op3/r_el_position/pid/p: 10.0
 * /robotis_op3/r_el_position/type: effort_controller...
 * /robotis_op3/r_hip_pitch_position/joint: r_hip_pitch
 * /robotis_op3/r_hip_pitch_position/pid/d: 0.0
 * /robotis_op3/r_hip_pitch_position/pid/i: 0.0
 * /robotis_op3/r_hip_pitch_position/pid/p: 50.0
 * /robotis_op3/r_hip_pitch_position/type: effort_controller...
 * /robotis_op3/r_hip_roll_position/joint: r_hip_roll
 * /robotis_op3/r_hip_roll_position/pid/d: 0.0
 * /robotis_op3/r_hip_roll_position/pid/i: 0.0
 * /robotis_op3/r_hip_roll_position/pid/p: 50.0
 * /robotis_op3/r_hip_roll_position/type: effort_controller...
 * /robotis_op3/r_hip_yaw_position/joint: r_hip_yaw
 * /robotis_op3/r_hip_yaw_position/pid/d: 0.0
 * /robotis_op3/r_hip_yaw_position/pid/i: 0.0
 * /robotis_op3/r_hip_yaw_position/pid/p: 50.0
 * /robotis_op3/r_hip_yaw_position/type: effort_controller...
 * /robotis_op3/r_knee_position/joint: r_knee
 * /robotis_op3/r_knee_position/pid/d: 0.0
 * /robotis_op3/r_knee_position/pid/i: 0.0
 * /robotis_op3/r_knee_position/pid/p: 50.0
 * /robotis_op3/r_knee_position/type: effort_controller...
 * /robotis_op3/r_sho_pitch_position/joint: r_sho_pitch
 * /robotis_op3/r_sho_pitch_position/pid/d: 0.0
 * /robotis_op3/r_sho_pitch_position/pid/i: 0.0
 * /robotis_op3/r_sho_pitch_position/pid/p: 10.0
 * /robotis_op3/r_sho_pitch_position/type: effort_controller...
 * /robotis_op3/r_sho_roll_position/joint: r_sho_roll
 * /robotis_op3/r_sho_roll_position/pid/d: 0.0
 * /robotis_op3/r_sho_roll_position/pid/i: 0.0
 * /robotis_op3/r_sho_roll_position/pid/p: 10.0
 * /robotis_op3/r_sho_roll_position/type: effort_controller...
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /use_sim_time: True

NODES
  /robotis_op3/
    controller_spawner (controller_manager/spawner)
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://home-desktop:11311/

process[gazebo-1]: started with pid [5211]
process[gazebo_gui-2]: started with pid [5216]
process[urdf_spawner-3]: started with pid [5219]
process[robotis_op3/controller_spawner-4]: started with pid [5222]
[INFO] [1529578037.509655, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
SpawnModel script started
[INFO] [1529578043.565231, 0.000000]: Loading model XML from ros parameter
[INFO] [1529578043.583066, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1529578043.723237049]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1529578043.723843141]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1529578046.000100, 0.000000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1529578046.384363074]: <robotNamespace> set to: //
[ INFO] [1529578046.384405091]: <topicName> set to: //robotis_op3/imu
[ INFO] [1529578046.384422908]: <frameName> set to: body_link
[ INFO] [1529578046.384458891]: <updateRateHZ> set to: 10
[ INFO] [1529578046.384481482]: <gaussianNoise> set to: 0
[ INFO] [1529578046.384508796]: <xyzOffset> set to: 0 0 0
[ INFO] [1529578046.384550433]: <rpyOffset> set to: 0 -0 0
[INFO] [1529578046.409340, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[urdf_spawner-3] process has finished cleanly
log file: /home/chen/.ros/log/f865344c-753f-11e8-bd81-4ccc6a2535ed/urdf_spawner-3*.log
[ INFO] [1529578048.819407833]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1529578048.872359197]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1529578050.450088569]: Loading gazebo_ros_control plugin
[ INFO] [1529578050.450162271]: Starting gazebo_ros_control plugin in namespace: /robotis_op3
[ INFO] [1529578050.451018701]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.

[ WARN] [1529578050.683675701]: Deprecated syntax, please prepend 'hardware_interface/' to 'EffortJointInterface' within the <hardwareInterface> tag in joint 'l_hip_yaw'.
...
[ INFO] [1529578050.867083155]: Loaded gazebo_ros_control.
[INFO] [1529578051.132854, 0.000000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1529578051.134339, 0.000000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1529578051.136048, 0.000000]: Loading controller: joint_state_controller
[INFO] [1529578051.300550, 0.000000]: Loading controller: l_hip_yaw_position
[INFO] [1529578051.359110, 0.000000]: Loading controller: l_hip_roll_position
[INFO] [1529578051.397653, 0.000000]: Loading controller: l_hip_pitch_position
[INFO] [1529578051.438047, 0.000000]: Loading controller: l_knee_position
[INFO] [1529578051.481300, 0.000000]: Loading controller: l_ank_roll_position
[INFO] [1529578051.525466, 0.000000]: Loading controller: l_ank_pitch_position
[INFO] [1529578051.563661, 0.000000]: Loading controller: r_hip_yaw_position
[INFO] [1529578051.607361, 0.000000]: Loading controller: r_hip_roll_position
[INFO] [1529578051.651552, 0.000000]: Loading controller: r_hip_pitch_position
[INFO] [1529578051.696437, 0.000000]: Loading controller: r_knee_position
[INFO] [1529578051.737859, 0.000000]: Loading controller: r_ank_roll_position
[INFO] [1529578051.783136, 0.000000]: Loading controller: r_ank_pitch_position
[INFO] [1529578051.829441, 0.000000]: Loading controller: l_sho_pitch_position
[INFO] [1529578051.870561, 0.000000]: Loading controller: l_sho_roll_position
[INFO] [1529578051.913285, 0.000000]: Loading controller: l_el_position
[INFO] [1529578051.948215, 0.000000]: Loading controller: r_sho_pitch_position
[INFO] [1529578051.985227, 0.000000]: Loading controller: r_sho_roll_position
[INFO] [1529578052.020623, 0.000000]: Loading controller: r_el_position
[INFO] [1529578052.065815, 0.000000]: Loading controller: head_pan_position
[INFO] [1529578052.107381, 0.000000]: Loading controller: head_tilt_position
[INFO] [1529578052.147909, 0.000000]: Controller Spawner: Loaded controllers: joint_state_controller, l_hip_yaw_position, l_hip_roll_position, l_hip_pitch_position, l_knee_position, l_ank_roll_position, l_ank_pitch_position, r_hip_yaw_position, r_hip_roll_position, r_hip_pitch_position, r_knee_position, r_ank_roll_position, r_ank_pitch_position, l_sho_pitch_position, l_sho_roll_position, l_el_position, r_sho_pitch_position, r_sho_roll_position, r_el_position, head_pan_position, head_tilt_position

```

#in third terminal
roslaunch op3_manager op3_gazebo.launch

```
ROS_MASTER_URI=http://home-desktop:11311/

process[op3_manager-1]: started with pid [7034]
[ INFO] [1529578258.339327628]: manager->init
[ WARN] [1529578258.365148053]: SET TO GAZEBO MODE!
/dev/ttyUSB0 added. (baudrate: 2000000)
[PortHandlerLinux::SetupPort] Error opening serial port!
(/dev/ttyUSB0) [ID:  1]         XM-430 added. 
(/dev/ttyUSB0) [ID:  2]         XM-430 added. 
(/dev/ttyUSB0) [ID:  3]         XM-430 added. 
(/dev/ttyUSB0) [ID:  4]         XM-430 added. 
(/dev/ttyUSB0) [ID:  5]         XM-430 added. 
(/dev/ttyUSB0) [ID:  6]         XM-430 added. 
(/dev/ttyUSB0) [ID:  7]         XM-430 added. 
(/dev/ttyUSB0) [ID:  8]         XM-430 added. 
(/dev/ttyUSB0) [ID:  9]         XM-430 added. 
(/dev/ttyUSB0) [ID: 10]         XM-430 added. 
(/dev/ttyUSB0) [ID: 11]         XM-430 added. 
(/dev/ttyUSB0) [ID: 12]         XM-430 added. 
(/dev/ttyUSB0) [ID: 13]         XM-430 added. 
(/dev/ttyUSB0) [ID: 14]         XM-430 added. 
(/dev/ttyUSB0) [ID: 15]         XM-430 added. 
(/dev/ttyUSB0) [ID: 16]         XM-430 added. 
(/dev/ttyUSB0) [ID: 17]         XM-430 added. 
(/dev/ttyUSB0) [ID: 18]         XM-430 added. 
(/dev/ttyUSB0) [ID: 19]         XM-430 added. 
(/dev/ttyUSB0) [ID: 20]         XM-430 added. 
(/dev/ttyUSB0) [ID:200]        OPEN-CR added. 
[ WARN] [1529578258.448333359]: Fail to load offset yaml.
[ WARN] [1529578258.785285918]: Head control - angle unit : 35
[ INFO] [1529578259.025127718]: Go to init pose
[ INFO] [1529578259.026752173]: Base Module is enabled
[ INFO] [1529578427.454403091]: Base Module is enabled
```

#in the fourth terminal
roslaunch op3_gui_demo op3_demo.launch

```
... logging to /home/chen/.ros/log/f865344c-753f-11e8-bd81-4ccc6a2535ed/roslaunch-home-desktop-7331.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://home-desktop:42078/

SUMMARY
========

PARAMETERS
 * /demo_config: /home/chen/catkin...
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /
    op3_demo_opc (op3_gui_demo/op3_gui_demo)

ROS_MASTER_URI=http://home-desktop:11311/

process[op3_demo_opc-1]: started with pid [7348]
[ INFO] [1529578380.011487246]: Initialized node handle for default demo
[ INFO] [1529578380.023344695]: Initialized node handle for preview walking
[ INFO] [1529578414.106802597]: Go to robot initial pose.
[ INFO] [1529578420.400453653]: Get current Mode
[ INFO] [1529578427.454093042]: Set Mode : head_control_module
```

**Comment by arixrobotics** [comment] 2018-06-25 03:09
Just to be sure, have you click the Start button in Gazebo?

**Comment by ROBOTIS-Kayman** [comment] 2018-06-27 08:50
I'm sorry. but I can't figure out what the problem is.
Could you provide me more information such as screenshots and the button you clicked on?

**Comment by arixrobotics** [comment] 2018-06-27 16:34
In the screenshot you @hayday100  provided, the start button on Gazebo is not pressed. Try clicking on it. Then only the simulation will start.

**Comment by hayday100** [comment] 2018-06-27 17:39
![image](https://user-images.githubusercontent.com/17373374/41989786-7643223e-7a0e-11e8-9c85-03ca52eb5f7a.png)
Thank you and I cannot believe that I ignored the Play button so many times.  Now that I pushed the Play button, the OP3 is responding but it will immediately lay down on its back and then stopped responding to the buttons again.  I tried the "get up (front)" and get up (back)" among other buttons but the simulation is stuck over there.  All programs are still running.  The side pane messages in the demo has "Succeed to start page 123", "failed to start page 122", etc.

**Comment by ROBOTIS-Kayman** [comment] 2018-06-28 00:54
I think there are no controllers for gazebo.
Did you install following packages?
```
# apt-get install ros-kinetic-ros-control
# apt-get install ros-kinetic-ros-controllers
# apt-get install ros-kinetic-gazebo-ros-control
```

**Comment by hayday100** [comment] 2018-06-28 16:01
Thank you.  That's what the problem is.  In the process of installing ros-kinetic-gazebo-ros-control I had to downgrade several libgazebo9 packages to libgazebo7.  Not that the version difference matters to me, I just wonder if it is because libgazebo9 has some issues with ros-kinetic-gazebo-ros-control which caused the broken packages issues I had.  I did some experiments with realtime camera video transfer after the last experiment with OP3 which might have caused the package issues.  Anyway, once problem at a time.  
The next question I have is a easier way to restart the robot simulation from initial pose after it falls from walking.  When OP3 falls face down, the "get up front" or "get up back" won't get it up.  So I have to restart gazebo, op3_manager and op3_demo all over right now.  And I also happen to run into another position when the robot becomes a box and get stuck.
![image](https://user-images.githubusercontent.com/17373374/42046024-f065f638-7aca-11e8-8a50-1c5f593a21d9.png)

**Comment by ROBOTIS-Kayman** [comment] 2018-07-02 04:06
- easier way to restart the robot simulation from initial pose after it falls from walking
How about Using `Reset Model Poses`(Edit -> Reset Model Poses) instead of restarting gazebo.

 - becoming a "box"
I think when OP3 is getting up, some friction problem is happened. I also do not know much about this issue. I'm sorry I can not help you any more.

**Comment by hayday100** [comment] 2018-07-03 23:19
It sounds like friction is a very common problem in simulators which give the robots difficulty to walk stably in a virtual environment.  The community NAO gazebo simulator seems to share the same problem.  When it comes to the comparison of OP3 with NAO, your strength is being open-source.  However, your robot is more expensive and there is no Python API for the time being.  OP3 gripping hands will add extra cost while NAO has gripping hands coming with it.   Any insights?

**Comment by robotpilot** [comment] 2018-07-09 22:31
Hi @hayday100,

Thank you for your consideration and supports. I would greatly appreciate it. Your comments are a great help to us, and your interest and support will allow us to grow an open project that we are working together. We will take the feedback of you and other customers and will do our best to make better products and support you. 

I'm going to close this until you update the issue with more information. You can reopen this issue to show this issue to the users whenever. Once again, thank you for your help and supports. :)

**Closed** 2018-07-09 22:32 UTC
Labels: question
